name: GitHub-Profile-3D-Contrib

on:
  schedule: # 每天 UTC 时间 0 点运行
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@v2.0.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Vogadero
        with:
          USERNAME: Vogadero
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contribution graph" || exit 0
          git push